//Create a new user
POST  http://localhost:5000/users
Content-Type: application/json; charset=UTF-8

{
    "email": "test1@gmail.com",
    "password": "testPassword",
    "firstName": "TestFirst",
    "lastName": "TestLast",
    "phone": "8468351681"
}

### 

//Get All Users
GET http://localhost:5000/user
### 

//Get User by Id
GET http://localhost:5000/users/4

###

// Get Events of User By Id
GET http://localhost:5000/users/4/events


###
//User Login
POST http://localhost:5000/users/login
Content-Type: application/json; charset=UTF-8

{
    "email": "test1@gmail.com",
    "password": "testPassword"
}


####

//Update user
PATCH  http://localhost:5000/users/2
Content-Type: application/json; charset=UTF-8

{
    "email": "kwamegilbert1114@gmail.com",
    "password": "1234",
    "firstName": "kWAME",
    "lastName": "oWUSU"
}

### Delete user
DELETE  http://localhost:5000/users/2


