//Create a new user
POST http://localhost:5000/events 
Content-Type: application/json; charset=UTF-8

{
  "name": "Ultimate Music Awards",
  "image": "https://example.com/images/ultimate-music-awards.png",
  "description": "Vote for the top musicians in this highly anticipated music awards event.",
  "organization_name": "Global Music Awards",
  "sender_id": "0203322110",
  "response_message": "Your vote for the Ultimate Music Awards has been recorded. Thank you for participating!",
  "organizer_share": "0.78",
  "admin_share": "0.22",
  "cost_per_vote": "3.00",
  "host": 1,
  "show_results": 1,
  "event_start": "2024-12-01 19:00:00",
  "event_end": "2024-12-25 23:00:00"
}

### 

//Get All Events
GET http://localhost:5000/hello
### 

//Get User by Id
GET http://localhost:5000/events/1

###

// Get Events of User By Id
GET http://localhost:5000/users/1/events

####

//Update user
PATCH http://localhost:5000/events/1
Content-Type: application/json; charset=UTF-8

{
  "name": "Miss Elegance Awards",
  "image": "https://example.com/images/miss-elegance.png",
  "description": "A prestigious awards ceremony recognizing the elegance and grace of participants.",
  "organization_name": "Elegance Foundation",
  "sender_id": "0245678901",
  "response_message": "Thank you for supporting the Miss Elegance Awards! Your contribution is appreciated.",
  "organizer_share": "0.75",
  "admin_share": "0.25",
  "cost_per_vote": "2.00",
  "host": 3,
  "show_results": 1,
  "event_start": "2024-11-15 17:00:00",
  "event_end": "2024-11-30 21:00:00"
}




### Delete user
DELETE  http://localhost:5000/events/11

###